baseURL = 'https://michaelfclements.github.io/'
languageCode = 'en-us'
title = "Michael's Resources"
theme = 'book'
author = 'Michael'
[params]
BookSearch = true
BookSection = 'resources'
[module]
[module.hugoVersion]
  extended = true
  min = "0.146.0"
[caches]
  [caches.images]
    dir = ':cacheDir/images'